// Mock data and default props for FlipCardGifter
// Generated by api-stripper on 2026-03-17T11:17:27.016Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/gifter/FlipCardGifter.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './FlipCardGifter';
// import { defaultProps } from './FlipCardGifter.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
