// Mock data and default props for HeroSection
// Generated by api-stripper on 2026-03-17T11:05:34.429Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/home/HeroSection.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './HeroSection';
// import { defaultProps } from './HeroSection.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
