// Mock data and default props for ZapigoSVG
// Generated by api-stripper on 2026-03-17T11:17:27.027Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/ui/ZapigoSVG.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './ZapigoSVG';
// import { defaultProps } from './ZapigoSVG.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
