// Mock data and default props for package
// Generated by api-stripper on 2026-03-17T11:05:34.437Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/hooks/affiliate/package.ts

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './package';
// import { defaultProps } from './package.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
