// Mock data and default props for about6
// Generated by api-stripper on 2026-03-17T11:17:27.015Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/about6.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './about6';
// import { defaultProps } from './about6.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
