// Mock data and default props for AddCoHostModal
// Generated by api-stripper on 2026-03-17T11:17:26.971Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/AddCoHostModal.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './AddCoHostModal';
// import { defaultProps } from './AddCoHostModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
