// Mock data and default props for AddGuestManuallyModal
// Generated by api-stripper on 2026-03-17T11:17:26.977Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/AddGuestManuallyModal.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
  // Data from useQuery — pass as prop
  eventData: undefined,
  // Loading state from useQuery
  isEventLoading: false,
  // Callback replacing createGuestMutation.mutate()
  onCreateGuest: () => {},
  // Pending state replacing createGuestMutation.isPending
  isCreateGuestPending: false,
  // User data from auth — pass as prop
  userData: { id: "mock-user-1", name: "Test User", email: "test@example.com" },
} as const;

// ---------------------------------------------------------------------------
// Mock data factories — customize these for realistic mockup data
// ---------------------------------------------------------------------------

export function createEventData(overrides: Record<string, any> = {}) {
  return {
    // TODO: Add realistic mock fields matching EventResponse
    id: "mock-1",
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Callback stubs — use these or provide custom handlers in mockups
// ---------------------------------------------------------------------------

export const onCreateGuest = (...args: any[]) => {
  console.log('onCreateGuest called with:', args);
};

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './AddGuestManuallyModal';
// import { defaultProps } from './AddGuestManuallyModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
