// Mock data and default props for AddressCard
// Generated by api-stripper on 2026-03-17T11:17:26.978Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/AddressCard.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './AddressCard';
// import { defaultProps } from './AddressCard.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
