// Mock data and default props for BottomNavbar
// Generated by api-stripper on 2026-03-17T11:17:26.979Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/BottomNavbar.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './BottomNavbar';
// import { defaultProps } from './BottomNavbar.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
