// Mock data and default props for BrandTicker
// Generated by api-stripper on 2026-03-17T11:17:26.980Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/BrandTicker.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './BrandTicker';
// import { defaultProps } from './BrandTicker.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
