// Mock data and default props for BulkMediaUpload
// Generated by api-stripper on 2026-03-17T11:05:34.398Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/BulkMediaUpload.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './BulkMediaUpload';
// import { defaultProps } from './BulkMediaUpload.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
