// Mock data and default props for ConfirmationModal
// Generated by api-stripper on 2026-03-17T11:17:26.982Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/ConfirmationModal.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './ConfirmationModal';
// import { defaultProps } from './ConfirmationModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
