// Mock data and default props for CustomTimePicker
// Generated by api-stripper on 2026-03-17T11:05:34.401Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/CustomTimePicker.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './CustomTimePicker';
// import { defaultProps } from './CustomTimePicker.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
