// Mock data and default props for ErrorDisplay
// Generated by api-stripper on 2026-03-17T11:17:26.989Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/ErrorDisplay.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './ErrorDisplay';
// import { defaultProps } from './ErrorDisplay.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
