// Mock data and default props for FlipCard
// Generated by api-stripper on 2026-03-17T11:05:34.406Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/FlipCard.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './FlipCard';
// import { defaultProps } from './FlipCard.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
