// Mock data and default props for FoodPreferenceModal
// Generated by api-stripper on 2026-03-17T11:17:26.992Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/FoodPreferenceModal.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
  // Data from useQuery — pass as prop
  eventConfigData: undefined,
  // Loading state from useQuery
  isLoading: false,
  // Data from useQuery — pass as prop
  eventData: undefined,
  // Loading state from useQuery
  isLoading: false,
  // Callback replacing updateEventMutation.mutate()
  onUpdateEvent: () => {},
  // Pending state replacing updateEventMutation.isPending
  isUpdateEventPending: false,
  // User data from auth — pass as prop
  userData: { id: "mock-user-1", name: "Test User", email: "test@example.com" },
} as const;

// ---------------------------------------------------------------------------
// Mock data factories — customize these for realistic mockup data
// ---------------------------------------------------------------------------

export function createEventConfigData(overrides: Record<string, any> = {}) {
  return {
    // TODO: Add realistic mock fields matching the data shape
    id: "mock-1",
    ...overrides,
  };
}

export function createEventData(overrides: Record<string, any> = {}) {
  return {
    // TODO: Add realistic mock fields matching EventResponse
    id: "mock-1",
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Callback stubs — use these or provide custom handlers in mockups
// ---------------------------------------------------------------------------

export const onUpdateEvent = (...args: any[]) => {
  console.log('onUpdateEvent called with:', args);
};

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './FoodPreferenceModal';
// import { defaultProps } from './FoodPreferenceModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
