// Mock data and default props for Footer
// Generated by api-stripper on 2026-03-17T11:17:26.993Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/Footer.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './Footer';
// import { defaultProps } from './Footer.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
