// Mock data and default props for GifterCard
// Generated by api-stripper on 2026-03-17T11:05:34.409Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/GifterCard.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './GifterCard';
// import { defaultProps } from './GifterCard.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
