// Mock data and default props for GlobalLoginModal
// Generated by api-stripper on 2026-03-17T11:05:34.410Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/GlobalLoginModal.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
  // Auth function — pass as prop
  previousPath: (...args: any[]) => { console.log('previousPath called', args); },
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './GlobalLoginModal';
// import { defaultProps } from './GlobalLoginModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
