// Mock data and default props for GuestResponseTypeModal
// Generated by api-stripper on 2026-03-17T11:17:26.997Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/GuestResponseTypeModal.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
  // Data from useQuery — pass as prop
  configResponse: undefined,
  // Loading state from useQuery
  isLoading: false,
  // Callback replacing updateRsvpMutation.mutate()
  onUpdateRsvp: () => {},
  // Pending state replacing updateRsvpMutation.isPending
  isUpdateRsvpPending: false,
} as const;

// ---------------------------------------------------------------------------
// Mock data factories — customize these for realistic mockup data
// ---------------------------------------------------------------------------

export function createConfigResponse(overrides: Record<string, any> = {}) {
  return {
    // TODO: Add realistic mock fields matching the data shape
    id: "mock-1",
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Callback stubs — use these or provide custom handlers in mockups
// ---------------------------------------------------------------------------

export const onUpdateRsvp = (...args: any[]) => {
  console.log('onUpdateRsvp called with:', args);
};

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './GuestResponseTypeModal';
// import { defaultProps } from './GuestResponseTypeModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
