// Mock data and default props for Header
// Generated by api-stripper on 2026-03-17T11:05:34.412Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/Header.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
  // Auth boolean state — pass as prop
  isAuthenticated: false,
  // User data from auth — pass as prop
  userData: { id: "mock-user-1", name: "Test User", email: "test@example.com" },
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './Header';
// import { defaultProps } from './Header.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
