// Mock data and default props for ImageOrVideoDialog
// Generated by api-stripper on 2026-03-17T11:17:26.999Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/ImageOrVideoDialog.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './ImageOrVideoDialog';
// import { defaultProps } from './ImageOrVideoDialog.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
