// Mock data and default props for ImageZoomDialog
// Generated by api-stripper on 2026-03-17T11:17:27.000Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/ImageZoomDialog.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './ImageZoomDialog';
// import { defaultProps } from './ImageZoomDialog.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
