// Mock data and default props for InfiniteScroll
// Generated by api-stripper on 2026-03-17T11:17:27.000Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/InfiniteScroll.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './InfiniteScroll';
// import { defaultProps } from './InfiniteScroll.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
