// Mock data and default props for LoadingSpinner
// Generated by api-stripper on 2026-03-17T11:05:34.415Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/LoadingSpinner.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './LoadingSpinner';
// import { defaultProps } from './LoadingSpinner.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
