// Mock data and default props for LoaderOverlay
// Generated by api-stripper on 2026-03-17T11:17:27.002Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/LoaderOverlay.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './LoaderOverlay';
// import { defaultProps } from './LoaderOverlay.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
