// Mock data and default props for LocationDetailsModal
// Generated by api-stripper on 2026-03-17T11:17:27.004Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/LocationDetailsModal.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './LocationDetailsModal';
// import { defaultProps } from './LocationDetailsModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
