// Mock data and default props for LocationAutocomplete
// Generated by api-stripper on 2026-03-17T11:17:27.003Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/LocationAutocomplete.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './LocationAutocomplete';
// import { defaultProps } from './LocationAutocomplete.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
