// Mock data and default props for LoginModal
// Generated by api-stripper on 2026-03-17T11:05:34.418Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/LoginModal.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
  // Auth function — pass as prop
  sendOtp: (...args: any[]) => { console.log('sendOtp called', args); },
  // Auth function — pass as prop
  verifyOtp: (...args: any[]) => { console.log('verifyOtp called', args); },
  // Auth function — pass as prop
  resendOtp: (...args: any[]) => { console.log('resendOtp called', args); },
  // Auth function — pass as prop
  updateUserProfile: (...args: any[]) => { console.log('updateUserProfile called', args); },
  // Auth boolean state — pass as prop
  isSendingOtp: false,
  // Auth boolean state — pass as prop
  isVerifyingOtp: false,
  // Auth boolean state — pass as prop
  isResendingOtp: false,
  // Auth boolean state — pass as prop
  isUpdatingProfile: false,
  // User data from auth — pass as prop
  userData: { id: "mock-user-1", name: "Test User", email: "test@example.com" },
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './LoginModal';
// import { defaultProps } from './LoginModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
