// Mock data and default props for MapPreview
// Generated by api-stripper on 2026-03-17T11:17:27.005Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/MapPreview.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './MapPreview';
// import { defaultProps } from './MapPreview.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
