// Mock data and default props for MenuDialog
// Generated by api-stripper on 2026-03-17T11:17:27.006Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/MenuDialog.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
  // Auth function — pass as prop
  logout: (...args: any[]) => { console.log('logout called', args); },
  // User data from auth — pass as prop
  userData: { id: "mock-user-1", name: "Test User", email: "test@example.com" },
  // Auth boolean state — pass as prop
  isAuthenticated: false,
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './MenuDialog';
// import { defaultProps } from './MenuDialog.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
