// Mock data and default props for OtpInput
// Generated by api-stripper on 2026-03-17T11:05:34.419Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/OtpInput.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './OtpInput';
// import { defaultProps } from './OtpInput.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
