// Mock data and default props for PageWrapper
// Generated by api-stripper on 2026-03-17T11:05:34.420Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/PageWrapper.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './PageWrapper';
// import { defaultProps } from './PageWrapper.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
