// Mock data and default props for PageLayout
// Generated by api-stripper on 2026-03-17T11:17:27.007Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/PageLayout.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
  // Auth function — pass as prop
  setPreviousPath: (...args: any[]) => { console.log('setPreviousPath called', args); },
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './PageLayout';
// import { defaultProps } from './PageLayout.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
