// Mock data and default props for ProductCard
// Generated by api-stripper on 2026-03-17T11:17:27.008Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/ProductCard.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './ProductCard';
// import { defaultProps } from './ProductCard.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
