// Mock data and default props for QuickInviteModal
// Generated by api-stripper on 2026-03-17T11:17:27.009Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/QuickInviteModal.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './QuickInviteModal';
// import { defaultProps } from './QuickInviteModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
