// Mock data and default props for ShareInviteModal
// Generated by api-stripper on 2026-03-17T11:17:27.010Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/ShareInviteModal.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
  // Data from useQuery — pass as prop
  shareLinkData: undefined,
  // Loading state from useQuery
  isShareLinkLoading: false,
} as const;

// ---------------------------------------------------------------------------
// Mock data factories — customize these for realistic mockup data
// ---------------------------------------------------------------------------

export function createShareLinkData(overrides: Record<string, any> = {}) {
  return {
    // TODO: Add realistic mock fields matching the data shape
    id: "mock-1",
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './ShareInviteModal';
// import { defaultProps } from './ShareInviteModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
