// Mock data and default props for SimpleResponsiveGallery
// Generated by api-stripper on 2026-03-17T11:17:27.011Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/SimpleResponsiveGallery.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './SimpleResponsiveGallery';
// import { defaultProps } from './SimpleResponsiveGallery.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
