// Mock data and default props for SuccessOverlay
// Generated by api-stripper on 2026-03-17T11:05:34.422Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/SuccessOverlay.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './SuccessOverlay';
// import { defaultProps } from './SuccessOverlay.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
