// Mock data and default props for Suggestions
// Generated by api-stripper on 2026-03-17T11:05:34.423Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/Suggestions.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './Suggestions';
// import { defaultProps } from './Suggestions.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
