// Mock data and default props for ThemeProvider
// Generated by api-stripper on 2026-03-17T11:17:27.013Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/ThemeProvider.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './ThemeProvider';
// import { defaultProps } from './ThemeProvider.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
