// Mock data and default props for ThemeDetailsModal
// Generated by api-stripper on 2026-03-17T11:17:27.012Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/ThemeDetailsModal.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './ThemeDetailsModal';
// import { defaultProps } from './ThemeDetailsModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
