// Mock data and default props for VideoHls
// Generated by api-stripper on 2026-03-17T11:05:34.425Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/VideoHls.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './VideoHls';
// import { defaultProps } from './VideoHls.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
