// Mock data and default props for party-kit
// Generated by api-stripper on 2026-03-17T11:05:34.438Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/hooks/party-kit.ts

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './party-kit';
// import { defaultProps } from './party-kit.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
