// Mock data and default props for use-breakpoint
// Generated by api-stripper on 2026-03-17T11:05:34.439Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/hooks/use-breakpoint.ts

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './use-breakpoint';
// import { defaultProps } from './use-breakpoint.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
