// Mock data and default props for use-toast
// Generated by api-stripper on 2026-03-17T11:17:27.033Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/hooks/use-toast.ts

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './use-toast';
// import { defaultProps } from './use-toast.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
