// Mock data and default props for useClearSession
// Generated by api-stripper on 2026-03-17T11:17:27.033Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/hooks/useClearSession.ts

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './useClearSession';
// import { defaultProps } from './useClearSession.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
