// Mock data and default props for useGiftFinder
// Generated by api-stripper on 2026-03-17T11:05:34.441Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/hooks/useGiftFinder.ts

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './useGiftFinder';
// import { defaultProps } from './useGiftFinder.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
