// Mock data and default props for useHeaderConfig
// Generated by api-stripper on 2026-03-17T11:05:34.442Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/hooks/useHeaderConfig.ts

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './useHeaderConfig';
// import { defaultProps } from './useHeaderConfig.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
