// Mock data and default props for useLoginModal
// Generated by api-stripper on 2026-03-17T11:17:27.035Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/hooks/useLoginModal.ts

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './useLoginModal';
// import { defaultProps } from './useLoginModal.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
