// Mock data and default props for usePreserveScroll
// Generated by api-stripper on 2026-03-17T11:05:34.443Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/hooks/usePreserveScroll.ts

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './usePreserveScroll';
// import { defaultProps } from './usePreserveScroll.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
