// Mock data and default props for useRsvp
// Generated by api-stripper on 2026-03-17T11:05:34.443Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/hooks/useRsvp.ts

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
  // Callback replacing createRsvpMutation.mutate()
  onCreateRsvp: () => {},
  // Pending state replacing createRsvpMutation.isPending
  isCreateRsvpPending: false,
  // User data from auth — pass as prop
  userData: { id: "mock-user-1", name: "Test User", email: "test@example.com" },
} as const;

// ---------------------------------------------------------------------------
// Callback stubs — use these or provide custom handlers in mockups
// ---------------------------------------------------------------------------

export const onCreateRsvp = (...args: any[]) => {
  console.log('onCreateRsvp called with:', args);
};

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './useRsvp';
// import { defaultProps } from './useRsvp.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
