// Mock data and default props for useVisitorTracking
// Generated by api-stripper on 2026-03-17T11:17:27.038Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/hooks/useVisitorTracking.ts

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
  // Auth function — pass as prop
  sessionId: (...args: any[]) => { console.log('sessionId called', args); },
  // Auth function — pass as prop
  setSessionId: (...args: any[]) => { console.log('setSessionId called', args); },
  // User data from auth — pass as prop
  userData: { id: "mock-user-1", name: "Test User", email: "test@example.com" },
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './useVisitorTracking';
// import { defaultProps } from './useVisitorTracking.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
