// Mock data and default props for NewProductCard
// Generated by api-stripper on 2026-03-17T11:17:27.026Z
// Source: /Users/dewanshshukla/Desktop/zapigo/zapigowebclient/src/components/product/NewProductCard.tsx

// ---------------------------------------------------------------------------
// Default props — spread these when rendering the component in mockups
// ---------------------------------------------------------------------------

export const defaultProps = {
} as const;

// ---------------------------------------------------------------------------
// Usage example in a mockup screen:
// ---------------------------------------------------------------------------
//
// import Component from './NewProductCard';
// import { defaultProps } from './NewProductCard.mock';
//
// export default function MockScreen() {
//   return <Component {...defaultProps} />;
// }
